spring.application.name=placementmanagement

server.port=8096

spring.datasource.url=jdbc:postgresql://localhost:5432/AtriaCG07
spring.datasource.username=postgres
spring.datasource.password=isedeptait

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect